### ISSUE TITLE
启动项目 无法匹配gbeata问题

### ISSUE THREAD

**Issue by mrgu1609** [anyone-yuren/react-antd-admin-pnpm#17]
Failed to resolve entry for package "gbeata".
![Snipaste_2024-01-03_11-13-09](https://github.com/anyone-yuren/react-antd-admin-pnpm/assets/23252621/7f830fdf-26df-4e66-acae-ee6fa0b0792c)

**Comment by anyone-yuren** [comment]
1. 可以先执行一下命令： `pnpm run build --filter gbeata`，因为目前gbeata对外暴露的main配置是lib/index。 也就是需要构建之后的代码。
2. 如果你想直接调试组件库gbeata的源码，可以在使用的地方，使用` import { xx } from 'gbeata/src'`的方式。

**Comment by anyone-yuren** [comment]
问题已修复：https://github.com/anyone-yuren/react-antd-admin-pnpm/pull/40
